# name: CI delete-token
# run-name: Delete Token
# on: 
#   workflow_run:
#     workflows:
#       - "CI setup-website"
#     types:
#       - "completed"
# jobs:
#   delete-token:
#     runs-on: ubuntu-latest
#     environment: dev
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v3
      
#       - name: Install terraform
#         run: |
#           sudo apt-get -y install unzip
#           wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
#           unzip terraform_1.3.7_linux_amd64.zip
#           sudo mv terraform /usr/local/bin/
      
#       - name: Destroy Terraform
#         env:
#           TF_VAR_cloudflare_api_token_create: '${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN_CREATE }}'
#           TF_VAR_cloudflare_email: '${{ secrets.TF_VAR_CLOUDFLARE_EMAIL }}'
#         run: |
#           sleep 80
#           cd token
#           terraform init
#           terraform destroy -auto-approve